version: "3"
services:
  frontend:
    image: frontend-image
    ports:
      - "3000:80"
  backend:
    build: ./Backend
    volumes:
      - ./Backend:/app/Backend
    image: backend-image
    ports:
      - "8000:8000"
